name: "🚀 Build and release"

on:
  push:
    branches:
      - master

jobs:
  Chromatic-storybook:
    runs-on: ubuntu-latest
    name: "Send updates of storybook to Chromatic"
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          workingDir: app
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
  Deploy:
    runs-on: ubuntu-latest
    name: "Deploy to Vercel"
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
